### ISSUE TITLE
CLI reporting incorrect version

### ISSUE THREAD

**Issue by ain** [jonschlinkert/add-banner#11]
__Steps to reproduce__:

1. Query version of the `add-banner`

__What happens__:

```
$ npm run add-banner --version
6.1.0
```

__What should happen__: `1.0.0` should be reported

**Comment by ain** [comment]
Regression from 073b1fbc9e9a811d67d9b320ed2c6dad4e5db91a that removed `commander`.

**Comment by doowb** [comment]
@ain that's because the `--version` flag is being passed to `npm` first... if you're using an `npm` script, you'll need to specify that the flags should be passed to `add-banner` using a double dash between the commands:

```
$ npm run add-banner -- --version
add-banner 1.0.0
```

If you globally install `add-banner` and run it directly, then it works without the extra double dash:

```
$ add-banner --version
add-banner 1.0.0
```
